server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            searchLocations: file:///D:/confsvr/src/main/resources/config/licensingservice